const NAVIGATOR = {
  LOGIN: 'LOGIN_FLOW',
  LANDING: 'LANDING_FLOW',
  HOME: 'HOME_FLOW',
  PROFILE: 'PROFILE_FLOW',
  ONBOARDING: 'ONBOARDING_FLOW',
  ONE_TIME_WIZARD: 'ONE_TIME_WIZARD_FLOW',
  TURN: 'TURN_FLOW',
};
const LOGIN_STACK = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  REGISTER_ADDITIONAL_DATES: 'REGISTER_ADDITIONAL_DATES',
  PASSWORD_RECOVERY_SCREEN: 'PASSWORD_RECOVERY_SCREEN',
  MAIL_VERIFICATION_SCREEN: 'MAIL_VERIFICATION_SCREEN',
  CODE_VERIFICATION: 'CODE_VERIFICATION',
};

const HOME_STACK = {
  HOME_SCREEN: 'HOME_SCREEN',
  HOSPITAL_SCREEN: 'HOSPITAL_SCREEN',
  EVENTS_SCREEN: 'EVENTS_SCREEN',
  BLOOD_BANK_SCREEN: 'BLOOD_BANK_SCREEN',
};
const TURN_STACK = {
  TURN_SCREEN: 'TURN_SCREEN',
  DATA_SCREEN: 'DATA_SCREEN',
};

const ONBOARDING_STACK = {
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
};

const PROFILE_STACK = {
  PROFILE_SCREEN: 'PROFILE',
  MY_DONATIONS_SCREEN: 'MY_DONATIONS',
  MY_SHIFTS_SCREEN: 'MY_SHIFTS',
  SETTINGS_SCREEN: 'SETTINGS',
  ALERTS_SCREEN: 'ALERTS',
  LOGOUT_SCREEN: 'LOGOUT',
};

const ONE_TIME_WIZARD_STACK = {
  ONE_TIME_SCREEN: 'ONE_TIME',
  TIPE_AND_FACTOR: 'TIPE_AND_FACTOR',
};
export default {
  NAVIGATOR,
  LOGIN_STACK,
  ONBOARDING_STACK,
  ONE_TIME_WIZARD_STACK,
  PROFILE_STACK,
  TURN_STACK,
  HOME_STACK,
};
