const NAVIGATOR = {
  LOGIN: 'LOGIN_FLOW',
  LANDING: 'LANDING_FLOW',
  PROFILE: 'PROFILE_FLOW',
  ONBOARDING: 'ONBOARDING_FLOW',
  ONE_TIME_WIZARD: 'ONE_TIME_WIZARD_FLOW',
  TURN: 'TURN_FLOW',
  QR: 'QR_FLOW',
};
const LOGIN_STACK = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  REGISTER_ADDITIONAL_DATES: 'REGISTER_ADDITIONAL_DATES',
  PASSWORD_RECOVERY_SCREEN: 'PASSWORD_RECOVERY_SCREEN',
  MAIL_VERIFICATION_SCREEN: 'MAIL_VERIFICATION_SCREEN',
  CODE_VERIFICATION: 'CODE_VERIFICATION',
  ACCOUNT_VERIFICATED_SCREEN: 'ACCOUNT_VERIFICATED'
};
const LANDING_STACK ={
  LANDING_STACK: 'LANDING_STACK',
}

const TAB_STACK = {
  TAB_STACK: 'TAB_STACK',
};

const TURN_STACK = {
  TURN_SCREEN: 'TURN_SCREEN',
  DATA_SCREEN: 'DATA_SCREEN',
};

const ONBOARDING_STACK = {
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
};

const PROFILE_STACK = {
  PROFILE_SCREEN: 'PROFILE',
  MY_DONATIONS_SCREEN: 'MY_DONATIONS',
  MY_SHIFTS_SCREEN: 'MY_SHIFTS',
  SETTINGS_SCREEN: 'SETTINGS',
  ALERTS_SCREEN: 'ALERTS',
  LOGOUT_SCREEN: 'LOGOUT',
};

const ONE_TIME_WIZARD_STACK = {
  ONE_TIME_SCREEN: 'ONE_TIME',
  TIPE_AND_FACTOR: 'TIPE_AND_FACTOR',
};

const QR_STACK = {
  QR_SCREEN: 'QR',
  PREV_FORM_SCREEN: 'PREV_FORM',
  FORM_VERIFICATE_DATA_SCREEN: 'FORM_VERIFICATE',
  FORM_HEALTH_STATE_SCREEN: 'FORM_HEALTH_STATE',
  FORM_OTHER_DATA_SCREEN: 'FORM_OTHER_DATA',
}

export default {
  NAVIGATOR,
  LOGIN_STACK,
  LANDING_STACK,
  ONBOARDING_STACK,
  ONE_TIME_WIZARD_STACK,
  PROFILE_STACK,
  TURN_STACK,
  TAB_STACK,
  QR_STACK,
};
