const NAVIGATOR = {
    LOGIN: 'LOGIN_FLOW',
    HOME: 'HOME_FLOW',
    LANDING: 'LANDING_FLOW',
    };
const LOGIN_STACK = {
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    PASSWORD_RECOVERY_SCREEN:'PASSWORD_RECOVERY_SCREEN',
    MAIL_VERIFICATION_SCREEN:'MAIL_VERIFICATION_SCREEN',
    };
const LANDING_STACK = {
    SETTINGS_SCREEN: 'SETTINGS'
}
export default {
    NAVIGATOR,
    LOGIN_STACK,
    LANDING_STACK
    };